# Practical 10

**Aim:** Demonstrate NumPy array creation, indexing, slicing, reshaping, broadcasting and mathematical operations on multidimensional arrays.

### 1. Array Creation

In [1]:
import numpy as np

a1 = np.array([10, 20, 30, 40, 50])
a2 = np.array([[2, 4, 6], [8, 10, 12]])

print("1D Array:", a1)
print("2D Array:\n", a2)

print("Zeros (3x3):\n", np.zeros((3, 3)))
print("Ones (2x4):\n", np.ones((2, 4)))
print("Arange (10 to 30, step 5):", np.arange(10, 35, 5))
print("Linspace (0 to 100, 5 points):", np.linspace(0, 100, 5))
print("Identity Matrix:\n", np.eye(2))

1D Array: [10 20 30 40 50]
2D Array:
 [[ 2  4  6]
 [ 8 10 12]]
Zeros (3x3):
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Ones (2x4):
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Arange (10 to 30, step 5): [10 15 20 25 30]
Linspace (0 to 100, 5 points): [  0.  25.  50.  75. 100.]
Identity Matrix:
 [[1. 0.]
 [0. 1.]]


### 2. Indexing and Slicing

In [2]:
arr = np.array([5, 15, 25, 35, 45, 55, 65])
print("Element at index 2:", arr[2])
print("Slice index 2 to 6:", arr[2:6])
print("Reverse array:", arr[::-1])

grid = np.array([[11, 12, 13], [14, 15, 16], [17, 18, 19]])
print("\nGrid:\n", grid)
print("Element at [2, 1]:", grid[2, 1])
print("Subgrid (first 2 rows & cols):\n", grid[:2, :2])
print("Last column:", grid[:, -1])

Element at index 2: 25
Slice index 2 to 6: [25 35 45 55]
Reverse array: [65 55 45 35 25 15  5]

Grid:
 [[11 12 13]
 [14 15 16]
 [17 18 19]]
Element at [2, 1]: 18
Subgrid (first 2 rows & cols):
 [[11 12]
 [14 15]]
Last column: [13 16 19]


### 3. Reshaping and Flattening

In [3]:
data = np.arange(1, 17)
print("Original:", data)

mat4x4 = data.reshape(4, 4)
print("4x4 Matrix:\n", mat4x4)

flat = mat4x4.flatten()
print("Flattened:", flat)

Original: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
4x4 Matrix:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Flattened: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]


### 4. Broadcasting

In [4]:
matrix = np.array([[5, 10, 15], [20, 25, 30]])
vec = np.array([1, 2, 3])

print("Matrix:\n", matrix)
print("Vector:", vec)
print("Matrix + Vector:\n", matrix + vec)
print("Matrix * 3:\n", matrix * 3)

Matrix:
 [[ 5 10 15]
 [20 25 30]]
Vector: [1 2 3]
Matrix + Vector:
 [[ 6 12 18]
 [21 27 33]]
Matrix * 3:
 [[15 30 45]
 [60 75 90]]


### 5. Mathematical Operations

In [5]:
m1 = np.array([[2, 3], [4, 5]])
m2 = np.array([[1, 2], [3, 4]])

print("Addition:\n", m1 + m2)
print("Multiplication:\n", m1 * m2)
print("Dot Product:\n", np.dot(m1, m2))

print("\nSum:", m1.sum())
print("Row-wise Sum:", m1.sum(axis=1))
print("Mean:", m1.mean())
print("Max Value:", m1.max())
print("Sqrt:\n", np.sqrt(m1))

Addition:
 [[3 5]
 [7 9]]
Multiplication:
 [[ 2  6]
 [12 20]]
Dot Product:
 [[11 16]
 [19 28]]

Sum: 14
Row-wise Sum: [5 9]
Mean: 3.5
Max Value: 5
Sqrt:
 [[1.41421356 1.73205081]
 [2.         2.23606798]]
